# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('In', models.CharField(max_length=20)),
                ('Out', models.CharField(max_length=20)),
                ('Duration', models.CharField(max_length=20)),
            ],
        ),
    ]
