# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='Duration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='In',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='Out',
            field=models.CharField(default='', max_length=20),
        ),
    ]
